# Generated by Django 6.0.5 on 2026-05-24 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название лекарства')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('monday', models.BooleanField(default=False, verbose_name='Понедельник')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Вторник')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Среда')),
                ('thursday', models.BooleanField(default=False, verbose_name='Четверг')),
                ('friday', models.BooleanField(default=False, verbose_name='Пятница')),
                ('saturday', models.BooleanField(default=False, verbose_name='Суббота')),
                ('sunday', models.BooleanField(default=False, verbose_name='Воскресенье')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MedicineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время приёма')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='main.medicine', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'Время приёма',
                'verbose_name_plural': 'Время приёма',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Чупакабрик', max_length=100, verbose_name='Имя питомца')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('health', models.PositiveIntegerField(default=100, verbose_name='Здоровье')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('missed_in_row', models.PositiveIntegerField(default=0, verbose_name='Пропусков подряд')),
                ('status', models.CharField(choices=[('happy', 'Счастлив'), ('normal', 'Обычный'), ('sad', 'Грустный'), ('dead', 'Умер')], default='normal', max_length=20, verbose_name='Состояние')),
                ('is_alive', models.BooleanField(default=True, verbose_name='Жив')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Имя на сайте')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='IntakeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_time', models.TimeField(verbose_name='Запланированное время')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('taken', 'Принято'), ('missed', 'Пропущено')], max_length=20, verbose_name='Статус')),
                ('marked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicine', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'История приёма',
                'verbose_name_plural': 'История приёма',
                'ordering': ['-date', '-planned_time'],
                'unique_together': {('user', 'medicine', 'planned_time', 'date')},
            },
        ),
    ]
